### ISSUE TITLE
Interface not consistent with response values

### ISSUE THREAD

**Issue by astinnos** [dragonchain-inc/dragonchain-sdk-node#82]
Hi,

The interface for a get status result is defined as
```
export interface L1DragonchainStatusResult {
  level: number
  cloud: string
  url: string
  region: string
  scheme: string
  wallet: string
  hashAlgo: string
  version: string
  encryptionAlgo: string
}
```
but when i call the endpoint i actually get 

```
{
  dragonchainName: string,
  dragonchainVersion: string, 
  level: string
}
```

Is the dragonchain backend due an update to bring responses in line with the new SDK's?

Thanks

**Comment by cheeseandcereal** [comment]
Hey, thanks for noticing that!

With our new major version of our SDK, there were some changes to the backend which have not yet been released to production.

When these changes go out, the current SDK responses will become inline with what dragonchain sends out.

We released the SDKs before the backend changes so that people currently using the SDKs could update and prepare, as the SDKs contain breaking changes.
